# Generated by Django 5.0.7 on 2024-08-03 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique_for_date='created_at', verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('deadline', models.DateTimeField()),
                ('create_at', models.DateField(auto_now=True)),
                ('categories', models.ManyToManyField(to='task_manager.category')),
            ],
        ),
        migrations.CreateModel(
            name='SUbTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название подзадачи')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('deadline', models.DateTimeField()),
                ('create_at', models.DateField(auto_now=True)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task_manager.task')),
            ],
        ),
    ]
