# Generated by Django 5.0.7 on 2024-08-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_subtask_status_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='create_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
