# Generated by Django 5.0.7 on 2024-08-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_tag_alter_category_options_alter_subtask_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In progress', 'In progress'), ('Done', 'Done'), ('Pending', 'Pending'), ('Blocked', 'Blocked')], default='New', max_length=50, null=True),
        ),
    ]
