# Generated by Django 5.0.7 on 2024-08-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_alter_subtask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In_progress', 'In_progress'), ('Done', 'Done'), ('Pending', 'Pending'), ('Blocked', 'Blocked')], default='New', max_length=50, null=True),
        ),
    ]
