# Generated by Django 5.0.7 on 2024-08-20 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0006_alter_subtask_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ['-created_at'], 'verbose_name': 'Subtask'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Task'},
        ),
        migrations.RenameField(
            model_name='subtask',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
